services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_CONFIG_SERVER_MODE=$PGADMIN_CONFIG_SERVER_MODE
      - PGADMIN_LISTEN_PORT=$PGADMIN_LISTEN_PORT
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=$PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
      # Number of values to trust for X-Forwarded-For
      - PROXY_X_FOR_COUNT = 1
      # Number of values to trust for X-Forwarded-Proto.
      - PROXY_X_PROTO_COUNT = 0
      # Number of values to trust for X-Forwarded-Host.
      - PROXY_X_HOST_COUNT = 0
      # Number of values to trust for X-Forwarded-Port.
      - PROXY_X_PORT_COUNT = 1
      # Number of values to trust for X-Forwarded-Prefix.
      - PROXY_X_PREFIX_COUNT = 0
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    links:
      - "postgres:pgsql-server"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
